# Software {-}

## Packages {-}

All the exercise are solved using R (ver. 3.4.2) has been used provided with
packages: `survival` (@R-survival) for the survival data analyses (reference
package), `survminer` (@R-survminer) for advance survival plot using `ggplot2`
(@R-ggplot2) package, `cmprsk` (@R-cmprsk) for competing risk, `rms` (@R-rms)
for additional features on regression modeling strategies (survival ones
included).

With regards to the data management, the collection of package `tidyverse`
(@R-tidyverse) is loaded, which includes: `dplyr` (@R-dplyr) for data
manipulation, `purrr` (@R-purrr) for functional programming, `readr` (R-readr)
for data import, `tidyr` (R-tidyr) for funtions to tidy the data, `tibble`
(R-tibble) to take advantage of the *tible* data frame class and `ggplot2` as a
interface for the Gramar of Grahics.

The present book was written in RMarkdown (R-rmarkdown), compiled using `knitr`
(@R-knitr) and rendered as an HTML book by `bookdown` (@R-bookdown).


## System Information {-}

All the code is compiled on a system with the following overall characteristics
and loaded packages.

```{r session_info}
devtools::session_info()
```
